#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : arandr
Version  : 0.1.10
Release  : 21
URL      : https://gitlab.com/arandr/arandr/-/archive/0.1.10/arandr-0.1.10.tar.bz2
Source0  : https://gitlab.com/arandr/arandr/-/archive/0.1.10/arandr-0.1.10.tar.bz2
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0
Requires: arandr-bin = %{version}-%{release}
Requires: arandr-data = %{version}-%{release}
Requires: arandr-license = %{version}-%{release}
Requires: arandr-locales = %{version}-%{release}
Requires: arandr-man = %{version}-%{release}
Requires: arandr-python = %{version}-%{release}
Requires: arandr-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi-docutils

%description
==========================
ARandR: Another XRandR GUI
==========================

%package bin
Summary: bin components for the arandr package.
Group: Binaries
Requires: arandr-data = %{version}-%{release}
Requires: arandr-license = %{version}-%{release}

%description bin
bin components for the arandr package.


%package data
Summary: data components for the arandr package.
Group: Data

%description data
data components for the arandr package.


%package license
Summary: license components for the arandr package.
Group: Default

%description license
license components for the arandr package.


%package locales
Summary: locales components for the arandr package.
Group: Default

%description locales
locales components for the arandr package.


%package man
Summary: man components for the arandr package.
Group: Default

%description man
man components for the arandr package.


%package python
Summary: python components for the arandr package.
Group: Default
Requires: arandr-python3 = %{version}-%{release}

%description python
python components for the arandr package.


%package python3
Summary: python3 components for the arandr package.
Group: Default
Requires: python3-core

%description python3
python3 components for the arandr package.


%prep
%setup -q -n arandr-0.1.10
cd %{_builddir}/arandr-0.1.10

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1649965111
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/arandr
cp %{_builddir}/arandr-0.1.10/COPYING %{buildroot}/usr/share/package-licenses/arandr/8624bcdae55baeef00cd11d5dfcfa60f68710a02
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
%find_lang arandr

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/arandr
/usr/bin/unxrandr

%files data
%defattr(-,root,root,-)
/usr/share/applications/arandr.desktop

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/arandr/8624bcdae55baeef00cd11d5dfcfa60f68710a02

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/arandr.1.gz
/usr/share/man/man1/unxrandr.1.gz

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*

%files locales -f arandr.lang
%defattr(-,root,root,-)

